// Portfolio data extracted from lyricvideo.tv, ughdstudios.com, umesh.design
// YouTube IDs sourced from the live portfolio embeds on lyricvideo.tv
//
// Optional `video` field: a hosted MP4 path (e.g. '/reels/<slug>.mp4',
// dropped in public/reels/). The VR focus view plays it with sound;
// without it the focus view shows the still artwork. YouTube can't be
// used here — it won't texture into WebGL inside a headset.
//
// Optional `vimeo` field: a Vimeo video ID, played as an iframe in the
// detail modal. Mutually exclusive with `youtube` in practice; if both
// are set the modal prefers `vimeo`. Like YouTube it can't texture into
// WebGL, so it's no use to the VR view — that still needs `video`.
//
// Optional `desc` field: hand-written copy for the detail modal. Overrides
// the generated sentence from describe().

export const projects = [
  {
    slug: 'imagine-dragons-sharks',
    client: 'Imagine Dragons',
    title: 'SHARKS',
    tags: ['LYRIC VIDEO', 'POP', 'MOTION'],
    year: 2022,
    youtube: '7j7twuejxvU',
    img: '/thumbs/imagine-dragons-sharks.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'camila-cabello-my-oh-my',
    client: 'Camila Cabello',
    title: 'MY OH MY FT. DABABY',
    tags: ['LYRIC VIDEO', 'POP'],
    year: 2020,
    youtube: 'nQNynY4A5m4',
    img: '/thumbs/camila-cabello-my-oh-my.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'fifty-cent-get-low',
    client: '50 Cent',
    title: 'GET LOW',
    tags: ['LYRIC VIDEO', 'RAP'],
    year: 2015,
    youtube: 'C3XWFJpeU4I',
    img: '/thumbs/fifty-cent-get-low.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'fisher-jlo-waiting-for-tonight',
    client: 'FISHER & J.LO',
    title: 'WAITING FOR TONIGHT',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2023,
    youtube: 'IC8p8LsvyhQ',
    img: '/thumbs/fisher-jlo-waiting-for-tonight.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'green-day-too-dumb-to-die',
    client: 'Green Day',
    title: 'TOO DUMB TO DIE',
    tags: ['LYRIC VIDEO', 'ROCK'],
    year: 2016,
    youtube: 'qh7QJ_jLam0',
    img: '/thumbs/green-day-too-dumb-to-die.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'james-hype-drums',
    client: 'James Hype',
    title: 'DRUMS FT. KIM PETRAS',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2023,
    youtube: 'I7mrN3Qt6TE',
    img: '/thumbs/james-hype-drums.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'zedd-funny',
    client: 'Zedd',
    title: 'FUNNY',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2020,
    youtube: 'JzpxJcJwDZ0',
    img: '/thumbs/zedd-funny.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'lil-tjay-countin-on-you',
    client: 'Lil Tjay',
    title: "COUNTIN' ON YOU — FAST X",
    tags: ['LYRIC VIDEO', 'RAP'],
    year: 2023,
    youtube: 'bo9TFyru_z4',
    img: '/thumbs/lil-tjay-countin-on-you.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'flo-rida-good-girls',
    client: 'Flo Rida',
    title: 'GOOD GIRLS ON VACATION',
    tags: ['LYRIC VIDEO', 'POP'],
    year: 2022,
    youtube: 'pULD5H0If7g',
    img: '/thumbs/flo-rida-good-girls.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'jeremih-tonight-belongs-to-u',
    client: 'Jeremih',
    title: 'TONIGHT BELONGS TO U!',
    tags: ['LYRIC VIDEO', 'R&B'],
    year: 2015,
    youtube: 'MiJGfKrZ6yA',
    img: '/thumbs/jeremih-tonight-belongs-to-u.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'imagine-dragons-natural',
    client: 'Imagine Dragons',
    title: 'NATURAL',
    tags: ['LYRIC VIDEO', 'ROCK'],
    year: 2018,
    youtube: 'V5M2WZiAy6k',
    img: '/thumbs/imagine-dragons-natural.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'train-call-me-sir',
    client: 'Train',
    title: 'CALL ME SIR FT. CAM',
    tags: ['LYRIC VIDEO', 'COUNTRY'],
    year: 2018,
    youtube: 'lv_kecbON_g',
    img: '/thumbs/train-call-me-sir.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'krewella-enjoy-the-ride',
    client: 'Krewella',
    title: 'ENJOY THE RIDE',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2016,
    youtube: 'T3puoynrExA',
    img: '/thumbs/krewella-enjoy-the-ride.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'jay-ray-heartless',
    client: 'Jay Ray',
    title: 'HEARTLESS — 3D LYRIC VIDEO',
    tags: ['LYRIC VIDEO', '3D', 'EDM'],
    year: 2025,
    youtube: 'uDAoI9b9eTs',
    img: '/thumbs/jay-ray-heartless.jpg',
    source: 'ughdstudios.com',
  },
  {
    slug: 'little-monstaz-omg',
    client: 'Little Monstaz',
    title: 'OMG — ANIMATION VIDEO',
    tags: ['MUSIC VIDEO', '2D ANIMATION'],
    year: 2024,
    youtube: 'vKgqieFlPso',
    img: '/thumbs/little-monstaz-omg.jpg',
    source: 'ughdstudios.com',
  },
  {
    slug: 'birdsongs-reality',
    client: 'The Birdsongs',
    title: 'REALITY',
    tags: ['LYRIC VIDEO', 'MOTION', 'POP'],
    year: 2021,
    youtube: 'HCoB4NCSX3c',
    img: '/thumbs/birdsongs-reality.jpg',
    source: 'umesh.design',
  },
  {
    slug: 'lonis-vibe-check',
    client: 'LÒNIS',
    title: 'VIBE CHECK',
    tags: ['LYRIC VIDEO', 'POP'],
    year: 2021,
    youtube: 'vt3iUEBZXX8',
    img: '/thumbs/lonis-vibe-check.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'hi-rez-hometown',
    client: 'Hi-Rez',
    title: 'HOMETOWN FT. RICK LYNN',
    tags: ['LYRIC VIDEO', 'RAP'],
    year: 2019,
    youtube: '7JR5VtAdNgc',
    img: '/thumbs/hi-rez-hometown.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'thrdlife-secure-the-bag',
    client: 'THRDL!FE',
    title: 'SECURE THE BAG',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2018,
    youtube: 'muYnol3gvz4',
    img: '/thumbs/thrdlife-secure-the-bag.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'connor-price-overnight',
    client: 'Connor Price',
    title: 'OVERNIGHT',
    tags: ['LYRIC VIDEO', 'RAP'],
    year: 2022,
    youtube: 'sEpkF6N9P5I',
    img: '/thumbs/connor-price-overnight.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'why-wolves-war-cry',
    client: 'Why Wolves',
    title: 'WAR CRY',
    tags: ['LYRIC VIDEO', 'ROCK'],
    year: 2020,
    youtube: 'lK0XwvPv1v4',
    img: '/thumbs/why-wolves-war-cry.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'parasite-inc-rollercoaster',
    client: 'Parasite Inc.',
    title: 'HEADF**K ROLLERCOASTER',
    tags: ['LYRIC VIDEO', 'METAL'],
    year: 2018,
    youtube: 'zD9ByRvK8YI',
    img: '/thumbs/parasite-inc-rollercoaster.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'cut-the-lights-too-bright',
    client: 'CUT THE L!GHTS',
    title: 'TOO BRIGHT',
    tags: ['LYRIC VIDEO', 'ROCK'],
    year: 2021,
    youtube: 'J_Ew5lA0WMg',
    img: '/thumbs/cut-the-lights-too-bright.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'aramis-code-of-the-warrior',
    client: 'Aramis',
    title: 'CODE OF THE WARRIOR',
    tags: ['LYRIC VIDEO', 'RAP'],
    year: 2021,
    youtube: '-1Pknev_hRc',
    img: '/thumbs/aramis-code-of-the-warrior.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'still-they-ride',
    client: 'Innovibrations',
    title: 'STILL THEY RIDE — JOURNEY COVER',
    tags: ['LYRIC VIDEO', 'ROCK'],
    year: 2022,
    youtube: '5Ve7taYklKU',
    img: '/thumbs/still-they-ride.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'tanzen-baile',
    client: 'Edin & Manuel Turizo',
    title: 'TANZEN / BAILE',
    tags: ['LYRIC VIDEO', 'POP', 'MOTION'],
    year: 2020,
    youtube: 'KyOny5elAso',
    img: '/thumbs/tanzen-baile.jpg',
    desc: 'German-Latin collaboration between Edin and Manuel Turizo, staged as a full iPhone screen recording. Two friends chat about a girl, scroll through her photos and stories, and finally open TikTok, where she is dancing to this very song. The lyrics appear as native parts of an iOS interface the team rebuilt from scratch for the animation, complete with animoji-style faces of both artists singing the track to each other in chat, something no real iPhone could actually do.',
    source: 'ughdstudios.com',
  },
  {
    slug: 'fuck-it-i-love-it',
    client: 'ILIRA',
    title: 'FUCK IT, I LOVE IT!',
    tags: ['LYRIC VIDEO', 'POP', '2D ANIMATION'],
    year: 2020,
    youtube: 'i1hAt45oB9o',
    img: '/thumbs/fuck-it-i-love-it.png',
    desc: 'ILIRA’s hit about falling blindly for a bad boy she knows she should leave. She sent over a photo of the cartoon tattoo on her forearm and asked whether it could come alive, so the studio built a full character and storyline from that single image and animated it into a bright, fast-moving cartoon video packed with playful transitions.',
    source: 'ughdstudios.com',
  },
  {
    slug: 'when-im-gone',
    client: 'UGHD Studios',
    title: "WHEN I'M GONE",
    tags: ['LYRIC VIDEO', 'POP', 'MOTION'],
    year: 2024,
    youtube: null,
    img: '/thumbs/when-im-gone.png',
    source: 'ughdstudios.com',
  },
  {
    slug: 'savannah-comfortable',
    client: 'Savannah',
    title: 'COMFORTABLE',
    tags: ['LYRIC VIDEO', 'R&B'],
    year: 2021,
    youtube: null,
    img: '/thumbs/savannah-comfortable.jpg',
    source: 'umesh.design',
  },
  {
    slug: 'lovin-promo',
    client: 'UGHD Studios',
    title: "LOVIN' — INSTAGRAM PROMO",
    tags: ['PROMO', 'SOCIAL'],
    year: 2021,
    youtube: null,
    img: '/thumbs/lovin-promo.png',
    source: 'umesh.design',
  },
  {
    slug: 'ladida-artwork',
    client: 'UGHD Studios',
    title: 'LADIDA — COVER ARTWORK',
    tags: ['ARTWORK', 'ILLUSTRATION'],
    year: 2025,
    youtube: null,
    img: '/thumbs/ladida-artwork.jpg',
    source: 'ughdstudios.com',
  },
  {
    slug: 'imagine-artwork',
    client: 'UGHD Studios',
    title: 'IMAGINE — COVER ARTWORK',
    tags: ['ARTWORK', 'DESIGN'],
    year: 2025,
    youtube: null,
    img: '/thumbs/imagine-artwork.webp',
    source: 'ughdstudios.com',
  },
  {
    slug: 'bep-concert-visuals',
    client: 'Black Eyed Peas',
    title: 'CONCERT VISUALS',
    tags: ['AI', 'MUSIC VIDEO', 'MOTION'],
    year: 2025,
    youtube: null,
    vimeo: '1218308402',
    img: '/thumbs/bep-concert-visuals.jpg',
    desc: 'Full concert visuals produced for the Black Eyed Peas’ 2025 tour, blending AI-generated imagery with iconic moments from their music videos. The result is a high-energy collage that reimagines decades of visuals into one cohesive live experience, honoring their legacy while pushing it forward.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'boots-giant-monsters',
    client: 'BOOTS',
    title: 'GIANT MONSTERS',
    tags: ['AI', 'LYRIC VIDEO', 'ALTERNATIVE', 'MOTION'],
    year: 2026,
    youtube: null,
    vimeo: '1218308706',
    img: '/thumbs/boots-giant-monsters.jpg',
    desc: 'Giant Monsters is a surreal music video built around giant cartoon monsters attacking the city. The visuals are set to a pulsing retro neon and eerie, marching rhythm, a surreal nightmare city, turning the relentless “boots, boots, boots” into a loud, cinematic descent into madness.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'j-mcallister-im-free',
    client: '1K PHEW ft. James McAllister',
    title: "I'M FREE",
    tags: ['AI', 'MUSIC VIDEO', '3D'],
    year: 2027,
    youtube: null,
    vimeo: '1218309002',
    img: '/thumbs/j-mcallister-im-free.jpg',
    desc: '3D animation style music video produced for 1K PHEW. An upcoming single, “I’M FREE”, featuring James McAllister, is a song about his back story, rise, and Faith Over Fear ministry work. The California beach themed visual is to be released next summer along with their dedicated FOF concert.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'cyberpunk-2077-tokyo-dreams',
    client: 'UGHD Studios',
    title: 'CYBERPUNK 2077 — TOKYO DREAMS',
    tags: ['AI', 'MOTION', '3D'],
    year: 2021,
    youtube: 'jkqtYypMl-A',
    img: '/thumbs/cyberpunk-2077-tokyo-dreams.jpg',
    desc: 'A Cyberpunk 2077 game inspired fan-fiction original created by the in-house production team. The story takes place in a dystopian Tokyo where society has unravelled under the grip of crime, corruption, and unchecked technological evolution. The Yakuza control the city from the shadows, while an enigmatic, benevolent force powered by a mysterious new tech lurks beneath the surface.',
    source: 'ughdstudios.com',
  },
  {
    slug: 'atiye-near-future',
    client: 'ATIYE',
    title: 'NEAR FUTURE',
    tags: ['AI', 'MUSIC VIDEO', 'MOTION'],
    year: 2026,
    youtube: null,
    vimeo: '1218307660',
    img: '/thumbs/atiye-near-future.jpg',
    desc: 'Full AI-generated music video produced for the young Turkish artist ATIYE, for the title track of her next album “Near Future” coming this fall. It’s a surreal visual heavily inspired by the lime and yellow colour accents of her cover artwork.',
    source: 'ughdstudios.com',
  },
  {
    slug: 'kharita-something-just-like-this',
    client: 'Kharita',
    title: 'SOMETHING JUST LIKE THIS',
    tags: ['AI', 'MUSIC VIDEO'],
    year: 2026,
    youtube: 'jGTVQLunzpg',
    img: '/thumbs/kharita-something-just-like-this.jpg',
    desc: 'Music video by Kharita performing a cover of “Something Just Like This” by The Chainsmokers & Coldplay. The 4K video is a high composited visualizer built with the help of AI tools while preserving the original brushstrokes and artform of Kharita, the singer.',
    source: 'ughdstudios.com',
  },
  {
    slug: 'ray-rhodes-when-i-needed-you',
    client: 'Ray Rhodes & Christian B',
    title: 'WHEN I NEEDED YOU',
    tags: ['LYRIC VIDEO', 'EDM', 'MOTION'],
    year: 2026,
    youtube: 'iEQvPyiuprU',
    img: '/thumbs/ray-rhodes-when-i-needed-you.jpg',
    desc: 'Summer-flavored EDM single from DJ duo Ray Rhodes and Christian B. The lyric video answers the song’s heartbreak with clean motion graphic animation, building its world out of breaking hearts and diamond motifs that split and reform in time with the track.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'her-fever-so-hollow',
    client: 'Her Fever',
    title: 'SO HOLLOW',
    tags: ['LYRIC VIDEO', 'ALTERNATIVE'],
    year: 2026,
    youtube: '6gbtaJV1ox0',
    img: '/thumbs/her-fever-so-hollow.jpg',
    desc: 'Debut single from Los Angeles alternative rock band Her Fever. “So Hollow” is a heavy, slow-burning song about being emptied out by a toxic love, its lyrics full of gallows, sorrow and sober minds, and the video was designed and animated to sit inside that darkness and let the words land as hard as the mix.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'grihastha-feeling-alive',
    client: 'Grihastha',
    title: 'FEELING ALIVE',
    tags: ['LYRIC VIDEO', 'METAL', 'MOTION'],
    year: 2025,
    youtube: '5sZCJ8OKzFw',
    img: '/thumbs/grihastha-feeling-alive.jpg',
    desc: 'A gritty, grinding single from Los Angeles hard rock band Grihastha. The lyric video channels the raw emotion of the track through a deliberately digital treatment of static, glitches and broken signals, while a stream of visuals pulses in the background tracing what it feels like to be alive.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'lunax-paradise',
    client: 'LUNAX',
    title: 'PARADISE FT. CERES',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2025,
    youtube: 'sf4xhkoMCvw',
    img: '/thumbs/lunax-paradise.jpg',
    desc: 'Official video for “Paradise” by LUNAX, one of Germany’s fastest-rising names in hardstyle, featuring vocals from CERES. The design grew out of her radical color choices and streetwear look, layering graffiti textures and paint brush strokes until the video feels sprayed straight onto the screen.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'christian-anderson-i-heard-the-bells',
    client: 'Christian Anderson Band',
    title: 'I HEARD THE BELLS (PEACE ON EARTH)',
    tags: ['LYRIC VIDEO', 'POP'],
    year: 2024,
    youtube: '0IazCu9Uzws',
    img: '/thumbs/christian-anderson-i-heard-the-bells.jpg',
    desc: 'A fresh arrangement of the classic Christmas song “I Heard the Bells on Christmas Day (Peace on Earth)” by the Christian Anderson Band. Turned around in just a few days for the holiday release, the lyric video keeps the design simple, warm and dynamic so the message of the song stays front and center.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'valerie-back-to-black',
    client: 'Valerie',
    title: 'BACK TO BLACK — AMY WINEHOUSE TRIBUTE',
    tags: ['LYRIC VIDEO', 'R&B'],
    year: 2024,
    youtube: 'fMEso15N9c8',
    img: '/thumbs/valerie-back-to-black.jpg',
    desc: 'Amy Winehouse’s “Back to Black” performed by Valerie, a tribute act dedicated to keeping her music alive. The video weaves real photographs into a restrained design of black, white and gold, a palette chosen to honor her elegance and her legacy.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'riki-lindhome-dont-google-mommy',
    client: 'Riki Lindhome',
    title: "DON'T GOOGLE MOMMY",
    tags: ['LYRIC VIDEO', 'POP'],
    year: 2024,
    youtube: 'gm5fhMlQu-c',
    img: '/thumbs/riki-lindhome-dont-google-mommy.jpg',
    desc: 'Comedy song by actress and musician Riki Lindhome, written from the perspective of a mother gently begging her newborn son never to type her name into a search engine. One of several videos the studio has produced for her, the parody has passed half a million views on YouTube alone.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'crispie-minelli-get-get-down',
    client: 'CRISPIE & Minelli',
    title: 'GET GET DOWN',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2022,
    youtube: 'suJNV5fcyg4',
    img: '/thumbs/crispie-minelli-get-get-down.jpg',
    desc: 'DJ duo CRISPIE joins forces with singer Minelli on a modern rework of Paul Johnson’s house classic “Get Get Down”, released through Universal Music. The lyric video keeps the energy simple and direct, with colorful, interactive type that bounces and snaps along with the groove.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'finch-masochist',
    client: '2 Engel & Charlie x FiNCH',
    title: 'MASOCHiST',
    tags: ['LYRIC VIDEO', 'RAP', '2D ANIMATION'],
    year: 2023,
    youtube: 'IrJFtY_qtxE',
    img: '/thumbs/finch-masochist.jpg',
    desc: 'German rap star FiNCH teams up with the duo 2 Engel & Charlie on “MASOCHiST”, a dark-humored track about loving what hurts you. The lyric video matches its bite with a deadpan cartoon style and fast, punchy character animation, and has climbed toward a million views on YouTube.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'ely-oaks-minelli-fantasy',
    client: 'Ely Oaks & Minelli',
    title: 'FANTASY',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2023,
    youtube: 'ev7003CXmAE',
    img: '/thumbs/ely-oaks-minelli-fantasy.jpg',
    desc: 'Club single from rising German producer Ely Oaks and vocalist Minelli. The lyric video is intentionally loud, a wall of vibrant color and rapid-fire animation locked to the beat, so every hit of the melody lands on screen as hard as it does in the mix.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'tash-blake-mannequin',
    client: 'Tash Blake',
    title: 'MANNEQUIN',
    tags: ['LYRIC VIDEO', 'POP', 'MOTION'],
    year: 2022,
    youtube: 'mu-MBi_KSQs',
    img: '/thumbs/tash-blake-mannequin.jpg',
    desc: '“Mannequin” follows a celebrity who keeps her partner like a statue, told through staged paparazzi shots and hidden camera footage. The studio handled the full edit, color grade and compositing, then finished it with CCTV-style screen effects and a digital lyric treatment that completes the surveillance look.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'hbz-high-sein',
    client: 'HBz x 2 Engel & Charlie',
    title: 'HIGH SEIN',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2022,
    youtube: 'DvBMSxX7lEI',
    img: '/thumbs/hbz-high-sein.jpg',
    desc: 'Official lyric video for “High Sein” by German DJ duo HBz together with 2 Engel & Charlie, one of their biggest hits with over 2.6 million views on YouTube alone. The visual meets the track’s energy head-on, driving a dense stream of psychedelic graphics and animation from the first drop to the last.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'luna-verlierer',
    client: 'LUNA',
    title: 'VERLIERER — RHODES AKUSTIK SESSION',
    tags: ['LYRIC VIDEO', 'POP', '3D', 'MOTION'],
    year: 2020,
    youtube: 'B0jaJQ7dipY',
    img: '/thumbs/luna-verlierer.jpg',
    desc: 'Acoustic session version of “Verlierer” by German pop artist LUNA, with an entire visual world expanded out of a single album artwork image. Long before AI tools existed the team extended the artwork by hand in Photoshop, cut a custom typeface to match her design, and drew sketchbook circles, wiggles and arrows around white and gold accents. Advanced camera tracking then turns it all into a 3D parallax that carries the viewer inside the cover.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'backclash-i-dont-wanna-fall-in-love',
    client: 'Backclash',
    title: "I DON'T WANNA FALL IN LOVE FT. SAACHI",
    tags: ['LYRIC VIDEO', 'POP', '2D ANIMATION'],
    year: 2018,
    youtube: '6_7r-2amFN0',
    img: '/thumbs/backclash-i-dont-wanna-fall-in-love.jpg',
    desc: 'Flat illustration lyric video for pop artist Backclash, designed as one continuous scroll through a fully illustrated home. The camera drifts past a turntable and headphones, stacks of vinyl, ice cream, polaroid string lights and a dressing table of make-up and glasses, with the lyrics tucked into the scenery along the way, before pulling back to reveal the entire house in the closing shot. Every illustration and animation was produced in-house.',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'veris-opening-night',
    client: 'VERIS',
    title: 'OPENING NIGHT',
    tags: ['LYRIC VIDEO', 'POP'],
    year: 2017,
    youtube: '0uFTdV8STzE',
    img: '/thumbs/veris-opening-night.jpg',
    desc: 'Released in 2017 but styled decades older, “Opening Night” plays like a late-night broadcast from another era. Vintage dance clips are cut so every step lands on the beat, wrapped in black-and-white CRT grain, retro titles and old-cinema effects, while the lyrics appear along the bottom of the frame in classic sing-along fashion.',
    source: 'lyricvideo.tv',
  },
];

export function describe(p) {
  // A hand-written `desc` always wins — the generated copy below is only a
  // fallback for entries that never got one.
  if (p.desc) return p.desc;
  const type = p.tags.includes('ARTWORK')
    ? 'Cover artwork designed'
    : p.tags.includes('PROMO')
      ? 'Social promo video produced'
      : p.tags.includes('MUSIC VIDEO')
        ? 'Animated music video produced'
        : 'Official lyric video designed and animated';
  return `${type} by UGHD Studios for ${p.client}. Crafted with high-end motion design and delivered for global release. Originally featured on ${p.source}.`;
}

export const filterTags = [
  { label: 'ALL' },
  { label: 'AI' },
  {
    label: 'LYRIC VIDEO',
    sub: ['POP', 'RAP', 'EDM', 'ROCK', 'METAL', 'R&B', 'COUNTRY', 'ALTERNATIVE'],
  },
  { label: 'MUSIC VIDEO' },
  { label: 'ANIMATION' },
  { label: 'MOTION' },
  { label: '3D' },
  { label: 'ARTWORK' },
  { label: 'PROMO' },
];
