// Portfolio data extracted from lyricvideo.tv, ughdstudios.com, umesh.design
// YouTube IDs sourced from the live portfolio embeds on lyricvideo.tv

export const projects = [
  {
    slug: 'imagine-dragons-sharks',
    client: 'Imagine Dragons',
    title: 'SHARKS',
    tags: ['LYRIC VIDEO', 'POP', 'MOTION'],
    year: 2022,
    youtube: '7j7twuejxvU',
    img: '/thumbs/imagine-dragons-sharks.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'camila-cabello-my-oh-my',
    client: 'Camila Cabello',
    title: 'MY OH MY FT. DABABY',
    tags: ['LYRIC VIDEO', 'POP'],
    year: 2020,
    youtube: 'nQNynY4A5m4',
    img: '/thumbs/camila-cabello-my-oh-my.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'fifty-cent-get-low',
    client: '50 Cent',
    title: 'GET LOW',
    tags: ['LYRIC VIDEO', 'RAP'],
    year: 2015,
    youtube: 'C3XWFJpeU4I',
    img: '/thumbs/fifty-cent-get-low.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'fisher-jlo-waiting-for-tonight',
    client: 'FISHER & J.LO',
    title: 'WAITING FOR TONIGHT',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2023,
    youtube: 'IC8p8LsvyhQ',
    img: '/thumbs/fisher-jlo-waiting-for-tonight.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'green-day-too-dumb-to-die',
    client: 'Green Day',
    title: 'TOO DUMB TO DIE',
    tags: ['LYRIC VIDEO', 'ROCK'],
    year: 2016,
    youtube: 'qh7QJ_jLam0',
    img: '/thumbs/green-day-too-dumb-to-die.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'james-hype-drums',
    client: 'James Hype',
    title: 'DRUMS FT. KIM PETRAS',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2023,
    youtube: 'I7mrN3Qt6TE',
    img: '/thumbs/james-hype-drums.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'zedd-funny',
    client: 'Zedd',
    title: 'FUNNY',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2020,
    youtube: 'JzpxJcJwDZ0',
    img: '/thumbs/zedd-funny.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'lil-tjay-countin-on-you',
    client: 'Lil Tjay',
    title: "COUNTIN' ON YOU — FAST X",
    tags: ['LYRIC VIDEO', 'RAP'],
    year: 2023,
    youtube: 'bo9TFyru_z4',
    img: '/thumbs/lil-tjay-countin-on-you.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'flo-rida-good-girls',
    client: 'Flo Rida',
    title: 'GOOD GIRLS ON VACATION',
    tags: ['LYRIC VIDEO', 'POP'],
    year: 2022,
    youtube: 'pULD5H0If7g',
    img: '/thumbs/flo-rida-good-girls.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'jeremih-tonight-belongs-to-u',
    client: 'Jeremih',
    title: 'TONIGHT BELONGS TO U!',
    tags: ['LYRIC VIDEO', 'R&B'],
    year: 2015,
    youtube: 'MiJGfKrZ6yA',
    img: '/thumbs/jeremih-tonight-belongs-to-u.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'imagine-dragons-natural',
    client: 'Imagine Dragons',
    title: 'NATURAL',
    tags: ['LYRIC VIDEO', 'ROCK'],
    year: 2018,
    youtube: 'V5M2WZiAy6k',
    img: '/thumbs/imagine-dragons-natural.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'train-call-me-sir',
    client: 'Train',
    title: 'CALL ME SIR FT. CAM',
    tags: ['LYRIC VIDEO', 'COUNTRY'],
    year: 2018,
    youtube: 'lv_kecbON_g',
    img: '/thumbs/train-call-me-sir.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'krewella-enjoy-the-ride',
    client: 'Krewella',
    title: 'ENJOY THE RIDE',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2016,
    youtube: 'T3puoynrExA',
    img: '/thumbs/krewella-enjoy-the-ride.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'jay-ray-heartless',
    client: 'Jay Ray',
    title: 'HEARTLESS — 3D LYRIC VIDEO',
    tags: ['LYRIC VIDEO', '3D', 'EDM'],
    year: 2025,
    youtube: 'uDAoI9b9eTs',
    img: '/thumbs/jay-ray-heartless.jpg',
    source: 'ughdstudios.com',
  },
  {
    slug: 'little-monstaz-omg',
    client: 'Little Monstaz',
    title: 'OMG — ANIMATION VIDEO',
    tags: ['MUSIC VIDEO', '2D ANIMATION'],
    year: 2024,
    youtube: 'vKgqieFlPso',
    img: '/thumbs/little-monstaz-omg.jpg',
    source: 'ughdstudios.com',
  },
  {
    slug: 'birdsongs-reality',
    client: 'The Birdsongs',
    title: 'REALITY',
    tags: ['LYRIC VIDEO', 'MOTION', 'POP'],
    year: 2021,
    youtube: 'HCoB4NCSX3c',
    img: '/thumbs/birdsongs-reality.jpg',
    source: 'umesh.design',
  },
  {
    slug: 'lonis-vibe-check',
    client: 'LÒNIS',
    title: 'VIBE CHECK',
    tags: ['LYRIC VIDEO', 'POP'],
    year: 2021,
    youtube: 'vt3iUEBZXX8',
    img: '/thumbs/lonis-vibe-check.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'hi-rez-hometown',
    client: 'Hi-Rez',
    title: 'HOMETOWN FT. RICK LYNN',
    tags: ['LYRIC VIDEO', 'RAP'],
    year: 2019,
    youtube: '7JR5VtAdNgc',
    img: '/thumbs/hi-rez-hometown.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'thrdlife-secure-the-bag',
    client: 'THRDL!FE',
    title: 'SECURE THE BAG',
    tags: ['LYRIC VIDEO', 'EDM'],
    year: 2018,
    youtube: 'muYnol3gvz4',
    img: '/thumbs/thrdlife-secure-the-bag.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'connor-price-overnight',
    client: 'Connor Price',
    title: 'OVERNIGHT',
    tags: ['LYRIC VIDEO', 'RAP'],
    year: 2022,
    youtube: 'sEpkF6N9P5I',
    img: '/thumbs/connor-price-overnight.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'why-wolves-war-cry',
    client: 'Why Wolves',
    title: 'WAR CRY',
    tags: ['LYRIC VIDEO', 'ROCK'],
    year: 2020,
    youtube: 'lK0XwvPv1v4',
    img: '/thumbs/why-wolves-war-cry.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'parasite-inc-rollercoaster',
    client: 'Parasite Inc.',
    title: 'HEADF**K ROLLERCOASTER',
    tags: ['LYRIC VIDEO', 'METAL'],
    year: 2018,
    youtube: 'zD9ByRvK8YI',
    img: '/thumbs/parasite-inc-rollercoaster.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'cut-the-lights-too-bright',
    client: 'CUT THE L!GHTS',
    title: 'TOO BRIGHT',
    tags: ['LYRIC VIDEO', 'ROCK'],
    year: 2021,
    youtube: 'J_Ew5lA0WMg',
    img: '/thumbs/cut-the-lights-too-bright.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'aramis-code-of-the-warrior',
    client: 'Aramis',
    title: 'CODE OF THE WARRIOR',
    tags: ['LYRIC VIDEO', 'RAP'],
    year: 2021,
    youtube: '-1Pknev_hRc',
    img: '/thumbs/aramis-code-of-the-warrior.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'still-they-ride',
    client: 'Innovibrations',
    title: 'STILL THEY RIDE — JOURNEY COVER',
    tags: ['LYRIC VIDEO', 'ROCK'],
    year: 2022,
    youtube: '5Ve7taYklKU',
    img: '/thumbs/still-they-ride.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'tanzen-baile',
    client: 'UGHD Studios',
    title: 'TANZEN / BAILE',
    tags: ['LYRIC VIDEO', 'EDM', 'MOTION'],
    year: 2024,
    youtube: null,
    img: '/thumbs/tanzen-baile.jpg',
    source: 'ughdstudios.com',
  },
  {
    slug: 'fuck-it-i-love-it',
    client: 'IRILA',
    title: 'FUCK IT, I LOVE IT!',
    tags: ['LYRIC VIDEO', 'POP', '2D ANIMATION'],
    year: 2024,
    youtube: null,
    img: '/thumbs/fuck-it-i-love-it.png',
    source: 'ughdstudios.com',
  },
  {
    slug: 'when-im-gone',
    client: 'UGHD Studios',
    title: "WHEN I'M GONE",
    tags: ['LYRIC VIDEO', 'POP', 'MOTION'],
    year: 2024,
    youtube: null,
    img: '/thumbs/when-im-gone.png',
    source: 'ughdstudios.com',
  },
  {
    slug: 'savannah-comfortable',
    client: 'Savannah',
    title: 'COMFORTABLE',
    tags: ['LYRIC VIDEO', 'R&B'],
    year: 2021,
    youtube: null,
    img: '/thumbs/savannah-comfortable.jpg',
    source: 'umesh.design',
  },
  {
    slug: 'lovin-promo',
    client: 'UGHD Studios',
    title: "LOVIN' — INSTAGRAM PROMO",
    tags: ['PROMO', 'SOCIAL'],
    year: 2021,
    youtube: null,
    img: '/thumbs/lovin-promo.png',
    source: 'umesh.design',
  },
  {
    slug: 'ladida-artwork',
    client: 'UGHD Studios',
    title: 'LADIDA — COVER ARTWORK',
    tags: ['ARTWORK', 'ILLUSTRATION'],
    year: 2025,
    youtube: null,
    img: '/thumbs/ladida-artwork.jpg',
    source: 'ughdstudios.com',
  },
  {
    slug: 'imagine-artwork',
    client: 'UGHD Studios',
    title: 'IMAGINE — COVER ARTWORK',
    tags: ['ARTWORK', 'DESIGN'],
    year: 2025,
    youtube: null,
    img: '/thumbs/imagine-artwork.webp',
    source: 'ughdstudios.com',
  },
  {
    slug: 'bep-concert-visuals',
    client: 'Black Eyed Peas',
    title: 'CONCERT VISUALS',
    tags: ['MUSIC VIDEO', 'MOTION'],
    year: 2022,
    youtube: null,
    img: '/thumbs/bep-concert-visuals.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'boots-giant-monsters',
    client: 'BOOTS',
    title: 'GIANT MONSTERS',
    tags: ['LYRIC VIDEO', 'ALTERNATIVE', 'MOTION'],
    year: 2019,
    youtube: null,
    img: '/thumbs/boots-giant-monsters.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'j-mcallister-im-free',
    client: 'J McAllister',
    title: "I'M FREE",
    tags: ['LYRIC VIDEO', 'POP'],
    year: 2024,
    youtube: null,
    img: '/thumbs/j-mcallister-im-free.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'ig-promo-reels',
    client: 'UGHD Studios',
    title: 'IG PROMO REELS',
    tags: ['PROMO', 'SOCIAL'],
    year: 2023,
    youtube: null,
    img: '/thumbs/ig-promo-reels.jpg',
    source: 'lyricvideo.tv',
  },
  {
    slug: 'cyberpunk-2077-tokyo-dreams',
    client: 'Cyberpunk 2077',
    title: 'TOKYO DREAMS',
    tags: ['MOTION', '3D'],
    year: 2021,
    youtube: null,
    img: '/thumbs/cyberpunk-2077-tokyo-dreams.jpg',
    source: 'lyricvideo.tv',
  },
];

export function describe(p) {
  const type = p.tags.includes('ARTWORK')
    ? 'Cover artwork designed'
    : p.tags.includes('PROMO')
      ? 'Social promo video produced'
      : p.tags.includes('MUSIC VIDEO')
        ? 'Animated music video produced'
        : 'Official lyric video designed and animated';
  return `${type} by UGHD Studios for ${p.client}. Crafted with high-end motion design and delivered for global release. Originally featured on ${p.source}.`;
}

export const filterTags = [
  { label: 'ALL' },
  {
    label: 'LYRIC VIDEO',
    sub: ['POP', 'RAP', 'EDM', 'ROCK', 'METAL', 'R&B', 'COUNTRY', 'ALTERNATIVE'],
  },
  { label: 'MUSIC VIDEO' },
  { label: 'ANIMATION' },
  { label: 'MOTION' },
  { label: '3D' },
  { label: 'ARTWORK' },
  { label: 'PROMO' },
];
